### PR TITLE
29-07-2020 Initial - add solution

### PR DESCRIPTION
**Pull request by MrCollection**
Hi I'm Added Solution and initial the environment

### CODE REVIEW

**Review by MrCollection — COMMENTED** [review]
I see these commits

**Review by MrCollection — COMMENTED** [review]
i change the review

**Review by MrCollection — COMMENTED** [review]
Ok. Rules Applied :)

**Review by mahdiafrad — APPROVED** [review]
I'm otherone

**Review by mahdiafrad — COMMENTED** [review]
I Confirm this

**Pull request merged**
